import { createHash, randomUUID } from 'node:crypto';
import { isIP } from 'node:net';
import { DatabaseSync } from 'node:sqlite';
import type { Application, AnswerValue, ApplicationState, CareerEvent, CareerMetrics, CareerProfile, JobOffer, MissingField, Outcome, Receipt, Resume, RunResult } from '../src/shared/career.ts';
import { ensureProtectedScope, LocalDataProtector, PROTECTED_SCOPES, repairCareerApplicationLastErrorLayout } from './data-protection.ts';

type Row = Record<string, unknown>;
const now = () => new Date().toISOString();
const plain = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const str = (v: unknown, name: string, max = 10000) => { if (typeof v !== 'string' || v.length > max) throw new CareerError(400, 'validation', `${name} invalide.`); return v.trim(); };
const obj = (v: unknown, name: string) => { if (!plain(v)) throw new CareerError(400, 'validation', `${name} invalide.`); return v; };
const only = (v: Record<string, unknown>, names: string[]) => { for (const k of Object.keys(v)) if (!names.includes(k)) throw new CareerError(400, 'validation', `Champ interdit : ${k}.`); };
const list = (v: unknown, name: string, max = 100) => { if (!Array.isArray(v) || v.length > max) throw new CareerError(400, 'validation', `${name} invalide.`); return v.map((x) => str(x, name, 500)); };
const j = <T>(v: unknown): T => JSON.parse(String(v)) as T;
const id = (v: unknown, name = 'Identifiant') => { const s = str(v, name, 64); if (!/^[a-f0-9-]{36}$/i.test(s)) throw new CareerError(400, 'validation', `${name} invalide.`); return s; };
const date = (v: unknown, name: string) => { const s = str(v, name, 40); if (s && !Number.isFinite(Date.parse(s))) throw new CareerError(400, 'validation', `${name} invalide.`); return s; };
const answers = (v: unknown): Record<string, AnswerValue> => { const o = obj(v, 'Réponses'); if (Object.keys(o).length > 200) throw new CareerError(400, 'validation', 'Trop de réponses.'); const r: Record<string, AnswerValue> = Object.create(null); for (const [k,x] of Object.entries(o)) { if (!k || k.length > 200 || k === '__proto__' || k === 'constructor' || k === 'prototype' || (typeof x !== 'boolean' && typeof x !== 'string') || (typeof x === 'string' && x.length > 2000)) throw new CareerError(400, 'validation', 'Réponse invalide.'); r[k] = x; } return r; };
const profileBlank = (): CareerProfile => ({ firstName:'',lastName:'',email:'',phone:'',city:'',country:'',address:'',postalCode:'',headline:'',summary:'',linkedinUrl:'',websiteUrl:'',skills:[],languages:[],experiences:[],education:[],preferences:{titles:[],locations:[],remote:false,contract:''},answers:{},updatedAt:'' });

export class CareerError extends Error { status:number; code:string; constructor(status: number, code: string, message: string) { super(message); this.name = 'CareerError'; this.status=status; this.code=code; } }

export function careerUrl(value: unknown, allowedTestOrigins: string[] = []): string {
  const raw = str(value, 'URL', 4000);
  let u: URL; try { u = new URL(raw); } catch { throw new CareerError(400,'validation','URL invalide.'); }
  const origin = u.origin;
  const test = allowedTestOrigins.includes(origin);
  if ((!test && u.protocol !== 'https:') || u.username || u.password || !u.hostname || !['https:','http:'].includes(u.protocol)) throw new CareerError(400,'unsafe_url','URL publique HTTPS requise.');
  const host = u.hostname.toLowerCase().replace(/^\[|\]$/g,'');
  if (!test && (host === 'localhost' || host.endsWith('.localhost') || host.endsWith('.local') || host.endsWith('.internal') || host === '0.0.0.0' || isIP(host) || /^10\.|^127\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\.|^192\.168\./.test(host))) throw new CareerError(400,'unsafe_url','URL publique requise.');
  u.hash = '';
  for (const key of [...u.searchParams.keys()]) if (/^(utm_.+|fbclid|gclid|msclkid|mc_cid|mc_eid)$/i.test(key)) u.searchParams.delete(key);
  return u.toString();
}

function receiptUrl(value: unknown, allowedTestOrigins: string[] = []): string {
  const u = new URL(careerUrl(value, allowedTestOrigins));
  for (const key of [...u.searchParams.keys()]) {
    if (/(?:token|secret|auth|session|code|key|password|credential|ticket|signature|jwt)/i.test(key)) u.searchParams.delete(key);
  }
  return u.toString();
}

export class CareerStore {
  db: DatabaseSync;
  private options: {allowedTestOrigins?: string[]; dataProtectionKey?: Buffer};
  private protectedData: LocalDataProtector;
  constructor(db: DatabaseSync, options: {allowedTestOrigins?: string[]; dataProtectionKey?: Buffer} = {}) {
    this.db=db; this.options=options; this.protectedData=new LocalDataProtector(options.dataProtectionKey);
    db.exec(`
      CREATE TABLE IF NOT EXISTS career_profile (id INTEGER PRIMARY KEY CHECK(id=1), value TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS career_resumes (id TEXT PRIMARY KEY, name TEXT NOT NULL, filename TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, sha256 TEXT NOT NULL, bytes BLOB NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS career_jobs (id TEXT PRIMARY KEY, url TEXT NOT NULL UNIQUE, title TEXT NOT NULL, company TEXT NOT NULL, location TEXT NOT NULL, description TEXT NOT NULL, source_url TEXT NOT NULL, discovered_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS career_applications (id TEXT PRIMARY KEY, job_id TEXT NOT NULL UNIQUE REFERENCES career_jobs(id), resume_id TEXT NOT NULL REFERENCES career_resumes(id), prospect_id TEXT, state TEXT NOT NULL, outcome TEXT NOT NULL, answers TEXT NOT NULL, missing_fields TEXT NOT NULL, notes TEXT NOT NULL, next_action_at TEXT NOT NULL, last_error TEXT NOT NULL, receipt TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, submitted_at TEXT);
      CREATE TABLE IF NOT EXISTS career_events (id TEXT PRIMARY KEY, application_id TEXT NOT NULL REFERENCES career_applications(id), kind TEXT NOT NULL, detail TEXT NOT NULL, source TEXT NOT NULL, happened_at TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS career_events_by_application ON career_events(application_id,happened_at DESC);
    `);
    const careerScope = PROTECTED_SCOPES.find((scope) => scope.name === 'career');
    if (!careerScope) throw new Error('Schéma de protection des candidatures absent.');
    repairCareerApplicationLastErrorLayout(db, options.dataProtectionKey);
    ensureProtectedScope(db, careerScope, options.dataProtectionKey);
  }
  private tx<T>(fn:()=>T):T { this.db.exec('BEGIN IMMEDIATE'); try { const r=fn(); this.db.exec('COMMIT'); return r; } catch(e) { this.db.exec('ROLLBACK'); throw e; } }
  private one(sql:string,...args:(string|number|null)[]):Row|undefined { return this.db.prepare(sql).get(...args) as Row|undefined; }
  private all(sql:string,...args:(string|number|null)[]):Row[] { return this.db.prepare(sql).all(...args) as Row[]; }
  private event(applicationId:string,kind:string,detail:string,source:'automation'|'user') { const eventId=randomUUID(); this.db.prepare('INSERT INTO career_events VALUES (?,?,?,?,?,?)').run(eventId,applicationId,kind,this.protectedData.writeText('career_events',eventId,'detail',detail.slice(0,1000)),source,now()); }
  getProfile(): CareerProfile { const row=this.one('SELECT value FROM career_profile WHERE id=1'); return row ? j<CareerProfile>(this.protectedData.readText('career_profile','1','value',row.value)) : profileBlank(); }
  saveProfile(input:unknown):CareerProfile { const o=obj(input,'Profil'); only(o,Object.keys(profileBlank())); const fields=['firstName','lastName','email','phone','city','country','address','postalCode','headline','summary','linkedinUrl','websiteUrl'] as const; const p=profileBlank(); for(const k of fields) p[k]=str(o[k]??'',k,k==='summary'?10000:1000); p.skills=list(o.skills??[],'Compétences'); p.languages=list(o.languages??[],'Langues'); const xp=o.experiences??[]; if(!Array.isArray(xp)||xp.length>100) throw new CareerError(400,'validation','Expériences invalides.'); p.experiences=xp.map((x)=>{const v=obj(x,'Expérience'); only(v,['company','title','start','end','description']);return {company:str(v.company??'','Entreprise',500),title:str(v.title??'','Poste',500),start:str(v.start??'','Début',100),end:str(v.end??'','Fin',100),description:str(v.description??'','Description',4000)};}); const ed=o.education??[]; if(!Array.isArray(ed)||ed.length>100) throw new CareerError(400,'validation','Études invalides.'); p.education=ed.map((x)=>{const v=obj(x,'Études'); only(v,['school','degree','start','end']);return {school:str(v.school??'','École',500),degree:str(v.degree??'','Diplôme',500),start:str(v.start??'','Début',100),end:str(v.end??'','Fin',100)};}); const pref=obj(o.preferences??{},'Préférences'); only(pref,['titles','locations','remote','contract']); p.preferences={titles:list(pref.titles??[],'Postes'),locations:list(pref.locations??[],'Lieux'),remote:pref.remote===true,contract:str(pref.contract??'','Contrat',500)}; if(pref.remote!==undefined&&typeof pref.remote!=='boolean') throw new CareerError(400,'validation','Télétravail invalide.'); p.answers=answers(o.answers??{}); const previous=this.getProfile(); const changed=JSON.stringify({...previous,updatedAt:''})!==JSON.stringify(p); if(changed&&this.one("SELECT 1 FROM career_applications WHERE state IN ('running','submitting') LIMIT 1")) throw new CareerError(409,'run_conflict','Profil utilisé par une candidature active.'); p.updatedAt=now(); this.tx(()=>{this.db.prepare('INSERT INTO career_profile(id,value) VALUES (1,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').run(this.protectedData.writeText('career_profile','1','value',JSON.stringify(p))); if(changed){for(const a of this.listApplications().filter(a=>a.state==='ready')){this.db.prepare("UPDATE career_applications SET state='draft',missing_fields=?,updated_at=? WHERE id=?").run(this.protectedData.writeText('career_applications',a.id,'missing_fields','[]'),now(),a.id);this.event(a.id,'profile_updated','Profil modifié : préparation à refaire','user');}}}); return p; }
  private resumeRow(r:Row):Resume { const resumeId=String(r.id); return {id:resumeId,name:this.protectedData.readText('career_resumes',resumeId,'name',r.name),filename:this.protectedData.readText('career_resumes',resumeId,'filename',r.filename),mime:this.protectedData.readText('career_resumes',resumeId,'mime',r.mime),size:Number(r.size),sha256:this.protectedData.readText('career_resumes',resumeId,'sha256',r.sha256),createdAt:String(r.created_at)}; }
  listResumes():Resume[] { return this.all('SELECT * FROM career_resumes ORDER BY created_at DESC').map(r=>this.resumeRow(r)); }
  saveResume(input:{name:string;filename:string;mime:string;bytes:Buffer}):Resume { const name=str(input.name,'Nom',200), filename=str(input.filename,'Fichier',255), mime=str(input.mime,'Type',100), bytes=input.bytes; if(!name||!filename||!Buffer.isBuffer(bytes)) throw new CareerError(400,'validation','CV invalide.'); if(bytes.length>10*1024*1024) throw new CareerError(413,'too_large','CV limité à 10 Mio.'); const ext=filename.toLowerCase().split('.').pop(); const pdf=ext==='pdf'&&mime==='application/pdf'&&bytes.subarray(0,5).toString()==='%PDF-'; const docx=ext==='docx'&&mime==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'&&bytes.subarray(0,4).equals(Buffer.from([0x50,0x4b,0x03,0x04]))&&bytes.includes(Buffer.from('word/')); if(!pdf&&!docx) throw new CareerError(400,'validation','CV PDF ou DOCX invalide.'); const rid=randomUUID(),stamp=now(),hash=createHash('sha256').update(bytes).digest('hex'); this.db.prepare('INSERT INTO career_resumes VALUES (?,?,?,?,?,?,?,?)').run(rid,this.protectedData.writeText('career_resumes',rid,'name',name),this.protectedData.writeText('career_resumes',rid,'filename',filename),this.protectedData.writeText('career_resumes',rid,'mime',mime),bytes.length,this.protectedData.writeText('career_resumes',rid,'sha256',hash),this.protectedData.writeBlob('career_resumes',rid,'bytes',bytes),stamp); return this.getResume(rid).meta; }
  getResume(resumeId:string):{meta:Resume;bytes:Buffer} { const rid=id(resumeId),r=this.one('SELECT * FROM career_resumes WHERE id=?',rid); if(!r) throw new CareerError(404,'not_found','CV introuvable.'); return {meta:this.resumeRow(r),bytes:this.protectedData.readBlob('career_resumes',rid,'bytes',r.bytes)}; }
  deleteResume(resumeId:string):void { this.getResume(resumeId); if(this.one('SELECT 1 FROM career_applications WHERE resume_id=?',resumeId)) throw new CareerError(409,'in_use','CV utilisé par une candidature.'); this.db.prepare('DELETE FROM career_resumes WHERE id=?').run(resumeId); }
  private jobRow(r:Row):JobOffer { return {id:String(r.id),url:String(r.url),title:String(r.title),company:String(r.company),location:String(r.location),description:String(r.description),sourceUrl:String(r.source_url),discoveredAt:String(r.discovered_at),updatedAt:String(r.updated_at)}; }
  saveJob(input:unknown):JobOffer { const o=obj(input,'Offre'); only(o,['url','title','company','location','description','sourceUrl']); const url=careerUrl(o.url,this.options.allowedTestOrigins),title=str(o.title,'Titre',500),company=str(o.company,'Entreprise',500),location=str(o.location??'','Lieu',500),description=str(o.description??'','Description',20000),sourceUrl=o.sourceUrl?careerUrl(o.sourceUrl,this.options.allowedTestOrigins):''; if(!title||!company) throw new CareerError(400,'validation','Titre et entreprise requis.'); const old=this.one('SELECT * FROM career_jobs WHERE url=?',url),stamp=now(); if(old) { this.db.prepare('UPDATE career_jobs SET title=?,company=?,location=?,description=?,source_url=?,updated_at=? WHERE id=?').run(title,company,location,description,sourceUrl,stamp,String(old.id)); return this.getJob(String(old.id)); } const jid=randomUUID(); this.db.prepare('INSERT INTO career_jobs VALUES (?,?,?,?,?,?,?,?,?)').run(jid,url,title,company,location,description,sourceUrl,stamp,stamp); return this.getJob(jid); }
  listJobs():JobOffer[] { return this.all('SELECT * FROM career_jobs ORDER BY updated_at DESC').map(r=>this.jobRow(r)); }
  getJob(jobId:string):JobOffer { const r=this.one('SELECT * FROM career_jobs WHERE id=?',id(jobId)); if(!r) throw new CareerError(404,'not_found','Offre introuvable.'); return this.jobRow(r); }
  private appRow(r:Row):Application { const applicationId=String(r.id); return {id:applicationId,jobId:String(r.job_id),resumeId:String(r.resume_id),prospectId:r.prospect_id===null?null:String(r.prospect_id),state:String(r.state) as ApplicationState,outcome:this.protectedData.readText('career_applications',applicationId,'outcome',r.outcome) as Outcome,answers:j(this.protectedData.readText('career_applications',applicationId,'answers',r.answers)),missingFields:j(this.protectedData.readText('career_applications',applicationId,'missing_fields',r.missing_fields)),notes:this.protectedData.readText('career_applications',applicationId,'notes',r.notes),nextActionAt:String(r.next_action_at),lastError:this.protectedData.readText('career_applications',applicationId,'last_error',r.last_error),receipt:r.receipt?j(this.protectedData.readText('career_applications',applicationId,'receipt',r.receipt)):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at),submittedAt:r.submitted_at===null?null:String(r.submitted_at)}; }
  createApplication(input:{jobId:string;resumeId:string;prospectId?:string}):Application { const jobId=id(input.jobId,'Offre'),resumeId=id(input.resumeId,'CV'); this.getJob(jobId); this.getResume(resumeId); const prospectId=input.prospectId?id(input.prospectId,'Prospect'):null; if(prospectId&&!this.one('SELECT 1 FROM prospects WHERE id=?',prospectId)) throw new CareerError(404,'not_found','Prospect introuvable.'); return this.tx(()=>{const existing=this.one('SELECT id FROM career_applications WHERE job_id=?',jobId); if(existing) return this.getApplication(String(existing.id)); const aid=randomUUID(),stamp=now(); this.db.prepare('INSERT INTO career_applications (id,job_id,resume_id,prospect_id,state,outcome,answers,missing_fields,notes,next_action_at,last_error,receipt,created_at,updated_at,submitted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(aid,jobId,resumeId,prospectId,'draft',this.protectedData.writeText('career_applications',aid,'outcome','active'),this.protectedData.writeText('career_applications',aid,'answers','{}'),this.protectedData.writeText('career_applications',aid,'missing_fields','[]'),this.protectedData.writeText('career_applications',aid,'notes',''),'',this.protectedData.writeText('career_applications',aid,'last_error',''),null,stamp,stamp,null); this.event(aid,'created','Candidature créée','user'); return this.getApplication(aid);}); }
  listApplications():Application[] { return this.all('SELECT * FROM career_applications ORDER BY updated_at DESC').map(r=>this.appRow(r)); }
  getApplication(appId:string):Application { const r=this.one('SELECT * FROM career_applications WHERE id=?',id(appId)); if(!r) throw new CareerError(404,'not_found','Candidature introuvable.'); return this.appRow(r); }
  updateApplication(appId:string,input:unknown):Application { const o=obj(input,'Candidature'); only(o,['resumeId','prospectId','answers','notes','nextActionAt','outcome']); const a=this.getApplication(appId); if(['running','submitting'].includes(a.state)) throw new CareerError(409,'active_or_uncertain','Candidature active.'); if(['submitted','uncertain'].includes(a.state)&&['resumeId','prospectId','answers'].some(k=>Object.hasOwn(o,k))) throw new CareerError(409,'immutable_application','Données de candidature figées après envoi ou soumission incertaine.'); const resumeId=o.resumeId===undefined?a.resumeId:id(o.resumeId,'CV'); this.getResume(resumeId); const prospectId=o.prospectId===undefined?a.prospectId:o.prospectId===null?null:id(o.prospectId,'Prospect'); if(prospectId&&!this.one('SELECT 1 FROM prospects WHERE id=?',prospectId)) throw new CareerError(404,'not_found','Prospect introuvable.'); const nextAnswers=o.answers===undefined?a.answers:answers(o.answers),notes=o.notes===undefined?a.notes:str(o.notes,'Notes',10000),nextActionAt=o.nextActionAt===undefined?a.nextActionAt:date(o.nextActionAt,'Relance'),outcome=o.outcome===undefined?a.outcome:o.outcome; if(typeof outcome!=='string'||!['active','interview','offer','rejected','withdrawn'].includes(outcome)) throw new CareerError(400,'validation','Résultat inconnu.'); const invalidated=resumeId!==a.resumeId||JSON.stringify(nextAnswers)!==JSON.stringify(a.answers); const state=invalidated&&a.state==='ready'?'draft':a.state; return this.tx(()=>{this.db.prepare('UPDATE career_applications SET resume_id=?,prospect_id=?,answers=?,notes=?,next_action_at=?,outcome=?,state=?,missing_fields=?,updated_at=? WHERE id=?').run(resumeId,prospectId,this.protectedData.writeText('career_applications',appId,'answers',JSON.stringify(nextAnswers)),this.protectedData.writeText('career_applications',appId,'notes',notes),nextActionAt,this.protectedData.writeText('career_applications',appId,'outcome',outcome),state,this.protectedData.writeText('career_applications',appId,'missing_fields',invalidated?'[]':JSON.stringify(a.missingFields)),now(),appId); if(outcome!==a.outcome) this.event(appId,'outcome',`Résultat : ${outcome}`,'user'); if(invalidated) this.event(appId,'updated','CV ou réponses modifiés','user'); return this.getApplication(appId);}); }
  claimRun(appId:string):Application { return this.tx(()=>{const a=this.getApplication(appId); if(!['draft','ready','needs_input','blocked','failed'].includes(a.state)) throw new CareerError(409,'run_conflict','Candidature déjà active, envoyée ou incertaine.'); this.db.prepare("UPDATE career_applications SET state='running',missing_fields=?,last_error=?,updated_at=? WHERE id=?").run(this.protectedData.writeText('career_applications',appId,'missing_fields','[]'),this.protectedData.writeText('career_applications',appId,'last_error',''),now(),appId); this.event(appId,'run_started','Préparation démarrée','automation'); return this.getApplication(appId);}); }
  markSubmitting(appId:string):void { this.tx(()=>{const a=this.getApplication(appId); if(a.state!=='running') throw new CareerError(409,'run_conflict','Soumission non autorisée.'); this.db.prepare("UPDATE career_applications SET state='submitting',updated_at=? WHERE id=?").run(now(),appId); this.event(appId,'submit_started','Clic final imminent','automation');}); }
  finishRun(appId:string,result:RunResult):Application { return this.tx(()=>{const a=this.getApplication(appId); if(!['running','submitting'].includes(a.state)) throw new CareerError(409,'run_conflict','Aucun run actif.'); if(!['ready','needs_input','blocked','submitted','uncertain','failed'].includes(result.state)) throw new CareerError(400,'validation','État invalide.'); const state=a.state==='submitting'&&result.state!=='submitted'?'uncertain':result.state; if(a.state==='running'&&state==='submitted') throw new CareerError(409,'run_conflict','Marqueur de soumission absent.'); const fields=Array.isArray(result.missingFields)?result.missingFields:[]; if(fields.length>100) throw new CareerError(400,'validation','Champs manquants invalides.'); const missing:MissingField[]=fields.map(f=>{const x=obj(f,'Champ');return {key:str(x.key,'Clé',200),label:str(x.label,'Libellé',500),required:x.required===true,type:['text','boolean','select','file','unknown'].includes(String(x.type))?x.type as MissingField['type']:'unknown',...(Array.isArray(x.options)?{options:list(x.options,'Options',100)}:{})};}); const message=str(result.message,'Message',1000); let receipt:Receipt|null=null; if(state==='submitted') { if(!result.receipt) throw new CareerError(400,'validation','Reçu requis.'); const r=obj(result.receipt,'Reçu'); receipt={url:receiptUrl(r.url,this.options.allowedTestOrigins),text:str(r.text,'Texte',1000),reference:str(r.reference,'Référence',200),observedAt:date(r.observedAt,'Date')||now()}; if(!receipt.text&&!receipt.reference) throw new CareerError(400,'validation','Preuve de réception requise.'); } const stamp=now(); this.db.prepare('UPDATE career_applications SET state=?,missing_fields=?,last_error=?,receipt=?,submitted_at=?,updated_at=? WHERE id=?').run(state,this.protectedData.writeText('career_applications',appId,'missing_fields',JSON.stringify(missing)),this.protectedData.writeText('career_applications',appId,'last_error',state==='ready'||state==='submitted'?'':message),receipt?this.protectedData.writeText('career_applications',appId,'receipt',JSON.stringify(receipt)):null,state==='submitted'?stamp:a.submittedAt,stamp,appId); this.event(appId,state,state==='submitted'?`Réception ${receipt?.reference||''}`:message,'automation'); return this.getApplication(appId);}); }
  recoverInterruptedRuns():void { this.tx(()=>{for(const a of this.listApplications().filter(x=>x.state==='running'||x.state==='submitting')) {const state=a.state==='submitting'?'uncertain':'failed'; this.db.prepare('UPDATE career_applications SET state=?,last_error=?,updated_at=? WHERE id=?').run(state,this.protectedData.writeText('career_applications',a.id,'last_error','Exécution interrompue.'),now(),a.id); this.event(a.id,'interrupted','Exécution interrompue','automation');}}); }
  resolveUncertain(appId:string,input:{resolution:'submitted'|'not_submitted';detail:string}):Application { const a=this.getApplication(appId); if(a.state!=='uncertain') throw new CareerError(409,'run_conflict','Candidature non incertaine.'); const detail=str(input.detail,'Vérification',1000); if(!detail) throw new CareerError(400,'validation','Détail de vérification requis.'); if(!['submitted','not_submitted'].includes(input.resolution)) throw new CareerError(400,'validation','Résolution invalide.'); return this.tx(()=>{const submitted=input.resolution==='submitted',stamp=now(); this.db.prepare('UPDATE career_applications SET state=?,last_error=?,submitted_at=?,updated_at=? WHERE id=?').run(submitted?'submitted':'draft',this.protectedData.writeText('career_applications',appId,'last_error',''),submitted?stamp:null,stamp,appId); this.event(appId,submitted?'manual_submitted':'manual_not_submitted',detail,'user'); return this.getApplication(appId);}); }
  listEvents():CareerEvent[] { return this.all('SELECT * FROM career_events ORDER BY happened_at DESC').map(r=>({id:String(r.id),applicationId:String(r.application_id),kind:String(r.kind),detail:this.protectedData.readText('career_events',String(r.id),'detail',r.detail),source:String(r.source) as 'automation'|'user',happenedAt:String(r.happened_at)})); }
  getMetrics():CareerMetrics { const apps=this.listApplications(); return {savedJobs:this.listJobs().length,applications:apps.length,submitted:apps.filter(a=>!!a.submittedAt).length,needsAttention:apps.filter(a=>['needs_input','blocked','uncertain','failed'].includes(a.state)).length,interviews:apps.filter(a=>a.outcome==='interview').length,offers:apps.filter(a=>a.outcome==='offer').length,rejected:apps.filter(a=>a.outcome==='rejected').length}; }
  seedDemo():void { if(this.listJobs().length) return; const profile=profileBlank(); this.saveProfile({...profile,firstName:'Camille',lastName:'Martin',email:'camille.martin@example.org',city:'Paris',country:'France',headline:'Développeuse full stack',skills:['TypeScript','React','Node.js']}); const bytes=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF'); const resume=this.saveResume({name:'CV général',filename:'cv-camille.pdf',mime:'application/pdf',bytes}); const j1=this.saveJob({url:'https://jobs.example.org/offres/ingenieur-logiciel',title:'Ingénieure logiciel',company:'Atelier Horizon',location:'Paris',description:'Poste fictif de démonstration.'}); const j2=this.saveJob({url:'https://jobs.example.org/offres/developpeur-web',title:'Développeuse web',company:'Maison Démo',location:'Lyon',description:'Poste fictif de démonstration.'}); this.createApplication({jobId:j1.id,resumeId:resume.id}); this.createApplication({jobId:j2.id,resumeId:resume.id}); }
}
