import { createCipheriv, createDecipheriv, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import type { CredentialSummary, VaultStatus } from '../src/shared/career.ts';
import { CareerError, careerUrl } from './career-store.ts';
import { ensureProtectedScope, LocalDataProtector, PROTECTED_SCOPES } from './data-protection.ts';

type Row=Record<string,unknown>;
export interface AIConfigSummary { baseUrl:string; model:string; updatedAt:string; }
export interface AIConfigSecret extends AIConfigSummary { apiKey:string; }
export interface FranceTravailConfig { clientId:string; clientSecret:string; scope:string; updatedAt:string; }
const stamp=()=>new Date().toISOString();
const check=(v:unknown,name:string,max=1000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new CareerError(400,'validation',`${name} invalide.`);return v.trim();};
const origin=(v:unknown,allowedTestOrigins:string[]=[])=>{const s=check(v,'Origine',500);let u:URL;try{u=new URL(careerUrl(s,allowedTestOrigins));}catch{throw new CareerError(400,'validation','Origine invalide.');}if(u.pathname!=='/'||u.search||u.hash)throw new CareerError(400,'validation','Origine exacte requise.');return u.origin;};
const seal=(key:Buffer, aad:string, value:string)=>{const nonce=randomBytes(12),c=createCipheriv('aes-256-gcm',key,nonce);c.setAAD(Buffer.from(aad));const ciphertext=Buffer.concat([c.update(value,'utf8'),c.final()]);return {nonce,ciphertext,tag:c.getAuthTag()};};
const open=(key:Buffer,aad:string,nonce:Buffer,ciphertext:Buffer,tag:Buffer)=>{const d=createDecipheriv('aes-256-gcm',key,nonce);d.setAAD(Buffer.from(aad));d.setAuthTag(tag);return Buffer.concat([d.update(ciphertext),d.final()]).toString('utf8');};
export class Vault {
  private key:Buffer|null=null;
  private protectedData:LocalDataProtector;
  db:DatabaseSync;
  private allowedTestOrigins:string[];
  constructor(db:DatabaseSync,options:{allowedTestOrigins?:string[];dataProtectionKey?:Buffer}={}){this.db=db;this.allowedTestOrigins=options.allowedTestOrigins??[];this.protectedData=new LocalDataProtector(options.dataProtectionKey);db.exec(`CREATE TABLE IF NOT EXISTS career_vault (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL, salt BLOB NOT NULL, nonce BLOB NOT NULL, ciphertext BLOB NOT NULL, tag BLOB NOT NULL); CREATE TABLE IF NOT EXISTS career_credentials (id TEXT PRIMARY KEY, origin TEXT NOT NULL, label TEXT NOT NULL, username TEXT NOT NULL, nonce BLOB NOT NULL, ciphertext BLOB NOT NULL, tag BLOB NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS career_ai_settings (id INTEGER PRIMARY KEY CHECK(id=1), base_url TEXT NOT NULL, model TEXT NOT NULL, nonce BLOB NOT NULL, ciphertext BLOB NOT NULL, tag BLOB NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS career_france_travail (id INTEGER PRIMARY KEY CHECK(id=1), nonce BLOB NOT NULL, ciphertext BLOB NOT NULL, tag BLOB NOT NULL, updated_at TEXT NOT NULL);`);const scope=PROTECTED_SCOPES.find((item)=>item.name==='vault');if(!scope)throw new Error('Schéma de protection des identifiants absent.');ensureProtectedScope(db,scope,options.dataProtectionKey);}
  private row(sql:string,...args:string[]):Row|undefined{return this.db.prepare(sql).get(...args) as Row|undefined;}
  status():VaultStatus{return {initialized:!!this.row('SELECT id FROM career_vault WHERE id=1'),unlocked:!!this.key};}
  initialize(passphrase:string):VaultStatus{if(this.status().initialized)throw new CareerError(409,'already_initialized','Coffre déjà initialisé.');if(typeof passphrase!=='string'||passphrase.length<12)throw new CareerError(400,'validation','Phrase secrète de 12 caractères minimum requise.');const salt=randomBytes(16),key=scryptSync(passphrase,salt,32,{N:32768,r:8,p:1,maxmem:64*1024*1024});const v=seal(key,'career-vault:v1:verifier','career-vault-check-v1');this.db.prepare('INSERT INTO career_vault VALUES (1,1,?,?,?,?)').run(salt,v.nonce,v.ciphertext,v.tag);this.key=key;return this.status();}
  unlock(passphrase:string):VaultStatus{const r=this.row('SELECT * FROM career_vault WHERE id=1');if(!r)throw new CareerError(409,'not_initialized','Coffre non initialisé.');if(typeof passphrase!=='string')throw new CareerError(400,'validation','Phrase secrète invalide.');const key=scryptSync(passphrase,Buffer.from(r.salt as Uint8Array),32,{N:32768,r:8,p:1,maxmem:64*1024*1024});try{const value=open(key,'career-vault:v1:verifier',Buffer.from(r.nonce as Uint8Array),Buffer.from(r.ciphertext as Uint8Array),Buffer.from(r.tag as Uint8Array));const expected=Buffer.from('career-vault-check-v1');if(!timingSafeEqual(Buffer.from(value),expected))throw new Error();}catch{key.fill(0);throw new CareerError(403,'bad_passphrase','Phrase secrète incorrecte ou coffre altéré.');}this.lock();this.key=key;return this.status();}
  lock():VaultStatus{if(this.key)this.key.fill(0);this.key=null;return this.status();}
  private requireKey():Buffer{if(!this.key)throw new CareerError(423,'vault_locked','Coffre verrouillé.');return this.key;}
  listCredentials():CredentialSummary[]{return (this.db.prepare('SELECT id,origin,label,username,updated_at FROM career_credentials ORDER BY updated_at DESC').all() as Row[]).map(r=>{const id=String(r.id);return {id,origin:this.protectedData.readText('career_credentials',id,'origin',r.origin),label:this.protectedData.readText('career_credentials',id,'label',r.label),username:this.protectedData.readText('career_credentials',id,'username',r.username),updatedAt:String(r.updated_at)};});}
  saveCredential(input:{origin:string;label:string;username:string;password:string}):CredentialSummary{const key=this.requireKey(),o=origin(input.origin,this.allowedTestOrigins),label=check(input.label,'Libellé',200),username=check(input.username,'Identifiant',500),password=input.password,id=randomUUID();if(typeof password!=='string'||password.length===0||password.length>10000)throw new CareerError(400,'validation','Mot de passe invalide.');const x=seal(key,`career-credential:v1:${id}:${o}`,password),updatedAt=stamp();this.db.prepare('INSERT INTO career_credentials VALUES (?,?,?,?,?,?,?,?)').run(id,this.protectedData.writeText('career_credentials',id,'origin',o),this.protectedData.writeText('career_credentials',id,'label',label),this.protectedData.writeText('career_credentials',id,'username',username),x.nonce,x.ciphertext,x.tag,updatedAt);return {id,origin:o,label,username,updatedAt};}
  deleteCredential(id:string):void{this.requireKey();const result=this.db.prepare('DELETE FROM career_credentials WHERE id=?').run(check(id,'Identifiant',64));if(result.changes===0)throw new CareerError(404,'not_found','Compte introuvable.');}
  getCredential(id:string,requestedOrigin:string):{username:string;password:string}{const key=this.requireKey(),credentialId=check(id,'Identifiant',64),r=this.row('SELECT * FROM career_credentials WHERE id=?',credentialId);if(!r)throw new CareerError(404,'not_found','Compte introuvable.');const o=origin(requestedOrigin,this.allowedTestOrigins),storedOrigin=this.protectedData.readText('career_credentials',credentialId,'origin',r.origin);if(o!==storedOrigin)throw new CareerError(403,'origin_mismatch','Origine du compte différente.');try{return {username:this.protectedData.readText('career_credentials',credentialId,'username',r.username),password:open(key,`career-credential:v1:${credentialId}:${o}`,Buffer.from(r.nonce as Uint8Array),Buffer.from(r.ciphertext as Uint8Array),Buffer.from(r.tag as Uint8Array))};}catch{throw new CareerError(403,'vault_corrupt','Compte chiffré illisible.');}}
  getAIConfigSummary():AIConfigSummary|null{const r=this.row('SELECT base_url,model,updated_at FROM career_ai_settings WHERE id=1');return r?{baseUrl:String(r.base_url),model:String(r.model),updatedAt:String(r.updated_at)}:null;}
  saveAIConfig(input:{baseUrl:string;model:string;apiKey:string}):AIConfigSummary{const key=this.requireKey(),baseUrl=check(input.baseUrl,'URL du fournisseur',2000),model=check(input.model,'Modèle',200),apiKey=input.apiKey;if(typeof apiKey!=='string'||!apiKey.trim()||apiKey.length>2000)throw new CareerError(400,'validation','Clé API invalide.');const aad=`career-ai:v1:${baseUrl}:${model}`,x=seal(key,aad,apiKey),updatedAt=stamp();this.db.prepare('INSERT INTO career_ai_settings VALUES (1,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET base_url=excluded.base_url,model=excluded.model,nonce=excluded.nonce,ciphertext=excluded.ciphertext,tag=excluded.tag,updated_at=excluded.updated_at').run(baseUrl,model,x.nonce,x.ciphertext,x.tag,updatedAt);return {baseUrl,model,updatedAt};}
  getAIConfig():AIConfigSecret{const key=this.requireKey(),r=this.row('SELECT * FROM career_ai_settings WHERE id=1');if(!r)throw new CareerError(404,'ai_not_configured','Fournisseur IA non configuré.');const baseUrl=String(r.base_url),model=String(r.model);try{return {baseUrl,model,updatedAt:String(r.updated_at),apiKey:open(key,`career-ai:v1:${baseUrl}:${model}`,Buffer.from(r.nonce as Uint8Array),Buffer.from(r.ciphertext as Uint8Array),Buffer.from(r.tag as Uint8Array))};}catch{throw new CareerError(403,'vault_corrupt','Clé du fournisseur IA illisible.');}}
  deleteAIConfig():void{this.requireKey();this.db.prepare('DELETE FROM career_ai_settings WHERE id=1').run();}
  franceTravailConfigSummary():{configured:boolean;scope?:string;updatedAt?:string}{const r=this.row('SELECT nonce,ciphertext,tag,updated_at FROM career_france_travail WHERE id=1');if(!r)return {configured:false};if(!this.key)return {configured:true,updatedAt:String(r.updated_at)};try{const value=JSON.parse(open(this.key,'career-france-travail:v1',Buffer.from(r.nonce as Uint8Array),Buffer.from(r.ciphertext as Uint8Array),Buffer.from(r.tag as Uint8Array))) as FranceTravailConfig;return {configured:true,scope:value.scope,updatedAt:String(r.updated_at)};}catch{throw new CareerError(403,'vault_corrupt','Configuration France Travail illisible.');}}
  saveFranceTravailConfig(input:{clientId:string;clientSecret:string;scope:string}):{configured:boolean;scope:string;updatedAt:string}{const key=this.requireKey(),clientId=check(input.clientId,'Identifiant client',500),clientSecret=input.clientSecret,scope=check(input.scope,'Périmètre API',500);if(typeof clientSecret!=='string'||!clientSecret.trim()||clientSecret.length>2000)throw new CareerError(400,'validation','Secret client invalide.');const updatedAt=stamp(),sealed=seal(key,'career-france-travail:v1',JSON.stringify({clientId,clientSecret,scope,updatedAt}));this.db.prepare('INSERT INTO career_france_travail VALUES (1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET nonce=excluded.nonce,ciphertext=excluded.ciphertext,tag=excluded.tag,updated_at=excluded.updated_at').run(sealed.nonce,sealed.ciphertext,sealed.tag,updatedAt);return {configured:true,scope,updatedAt};}
  getFranceTravailConfig():FranceTravailConfig{const key=this.requireKey(),r=this.row('SELECT nonce,ciphertext,tag,updated_at FROM career_france_travail WHERE id=1');if(!r)throw new CareerError(409,'source_not_configured','Configurez l’accès API France Travail.');try{return {...JSON.parse(open(key,'career-france-travail:v1',Buffer.from(r.nonce as Uint8Array),Buffer.from(r.ciphertext as Uint8Array),Buffer.from(r.tag as Uint8Array))) as FranceTravailConfig,updatedAt:String(r.updated_at)};}catch{throw new CareerError(403,'vault_corrupt','Configuration France Travail illisible.');}}
  deleteFranceTravailConfig():void{this.requireKey();this.db.prepare('DELETE FROM career_france_travail WHERE id=1').run();}
}
